explainer_saving_dir: ''
explainer_name: 'refine'
explanation_result_dir: 'refine'
explainer_saving_name: 'refine.pth'
superadditive_ext: False
sample_method: 'random'
num_samples: -1
num_hops: 4

evaluation:
  subgraph_building_method: 'split'

param:
  ba_2motifs:
    epoch: 1
    lr: 0.0003
    max_ex_size: -1
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  mutag0:
    epoch: 20
    lr: 1e-2
    max_ex_size: -1
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  benzene:
    epoch: 20
    lr: 1e-2
    max_ex_size: -1
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  ba_house_grid:
    epoch: 20
    lr: 1e-2
    max_ex_size: -1
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  ba_house_and_grid:
    epoch: 20
    lr: 1e-2
    max_ex_size: -1
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  ba_house_or_grid:
    epoch: 20
    lr: 1e-2
    max_ex_size: -1
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  mnist75sp:
    epoch: 2
    lr: 1e-3
    max_ex_size: -1
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  spmotif:
    epoch: 20
    lr: 1e-2
    max_ex_size: -1
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  graph_sst2:
    epoch: 20
    lr: 1e-2
    max_ex_size: 0.3
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  graph_sst5:
    epoch: 20
    lr: 1e-2
    max_ex_size: 0.3
    tau: 0.1
    sparsity: 0.5
    gamma: 5
  twitter:
    epoch: 20
    lr: 1e-2
    max_ex_size: 0.3
    tau: 0.1
    sparsity: 0.5
    gamma: 5
