explanation_result_dir: ''
explainer_name: 'same'

param:
  bbbp:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 12
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 5
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  ba_shapes:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 20
    local_raduis: 4
    sample_num: 100
    reward_method: 'Nc_mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 5
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  graph_sst2:
    rollout: 20
    high2low: False
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 12
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 3
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 0.3
  graph_sst5:
    rollout: 20
    high2low: False
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 12
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 3
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 0.3
  twitter:
    rollout: 20
    high2low: False
    c_puct: 5.0
    min_atoms: 5
    expand_atoms: 20
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 3
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 0.3
  ba_2motifs:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 20
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 3
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  mnist75sp:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 20
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 3
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  spmotif:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 20
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 3
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  ba_house_grid:
    rollout: 20
    high2low: True
    c_puct: 20.0
    min_atoms: 5
    expand_atoms: 40
    local_raduis: 5
    sample_num: 200
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 6
    candidate_size: 10
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  ba_house_and_grid:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 40
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 5
    candidate_size: 10
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  ba_house_or_grid:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 20
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 3
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  benzene:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 20
    local_raduis: 4
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 3
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  mutag:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 4
    expand_atoms: 20
    local_raduis: 5
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 2
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  mutag0:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 4
    expand_atoms: 20
    local_raduis: 5
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 2
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
  bace:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 4
    expand_atoms: 20
    local_raduis: 5
    sample_num: 100
    reward_method: 'mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True
    single_explanation_size: 2
    candidate_size: 7
    explanation_exploration_method: 'permutation'
    max_ex_size: 5
