gnn_saving_dir: 'checkpoints'
gnn_name: 'gat'
add_self_loop: False


param:
  mnist75sp:
    learning_rate: 0.001
    weight_decay: 0.0005
    milestones: None
    gamma: None
    batch_size: 256
    num_epochs: 1000
    num_early_stop: 100
    gat_dropout: 0 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 32
      - 32
      - 32
    gnn_dropout: 0.0
    add_self_loop: False
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'mean'
    fc_latent_dim: []
    concate: False
  benzene:
    learning_rate: 0.001
    weight_decay: 0.0005
    milestones: None
    gamma: None
    batch_size: 256
    num_epochs: 1000
    num_early_stop: 100
    gat_dropout: 0 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 32
      - 32
      - 32
    gnn_dropout: 0.0
    add_self_loop: False
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'mean'
    fc_latent_dim: []
    concate: False
  mutag0:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 256
    num_epochs: 1000
    num_early_stop: 100
    gat_dropout: 0 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 128
      - 128
      - 128
    gnn_dropout: 0.0
    add_self_loop: False
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'max'
    fc_latent_dim: []
    concate: False
  ba_2motifs:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 64
    num_epochs: 1000
    num_early_stop: 100
    gat_dropout: 0 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 100
      - 100
      - 100
    gnn_dropout: 0.0
    add_self_loop: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'mean'
    fc_nonlinear: 'relu'
    fc_latent_dim: []
    concate: False
  ba_house_grid:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 64
    num_epochs: 1000
    num_early_stop: 100
    gat_dropout: 0 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 100
      - 100
      - 100
    gnn_dropout: 0.0
    add_self_loop: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'mean'
    fc_nonlinear: 'relu'
    fc_latent_dim: []
    concate: False
  ba_house_and_grid:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 64
    num_epochs: 1000
    num_early_stop: 100
    gat_dropout: 0 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 100
      - 100
      - 100
    gnn_dropout: 0.0
    add_self_loop: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'mean'
    fc_nonlinear: 'relu'
    fc_latent_dim: []
    concate: False
  ba_house_or_grid:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 64
    num_epochs: 1000
    num_early_stop: 100
    gat_dropout: 0 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 100
      - 100
      - 100
    gnn_dropout: 0.0
    add_self_loop: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'mean'
    fc_nonlinear: 'relu'
    fc_latent_dim: []
    concate: False
  spmotif:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 64
    num_epochs: 1000
    num_early_stop: 100
    gat_dropout: 0 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 100
      - 100
      - 100
    gnn_dropout: 0.0
    add_self_loop: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'mean'
    fc_nonlinear: 'relu'
    fc_latent_dim: []
    concate: False
  graph_sst2:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 256
    num_epochs: 50
    num_early_stop: 10
    gat_dropout: 0.6 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 128
      - 128
      - 128
    gnn_dropout: 0.0
    add_self_loop: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'max'
    fc_latent_dim: []
  graph_sst5:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 256
    num_epochs: 50
    num_early_stop: 10
    gat_dropout: 0.6 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 128
      - 128
      - 128
    gnn_dropout: 0.0
    add_self_loop: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'max'
    fc_latent_dim: []
  twitter:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 256
    num_epochs: 100
    num_early_stop: 100
    gat_dropout: 0.6 
    gat_heads: 10
    gat_hidden: 10
    gat_concate: True
    gnn_latent_dim:
      - 128
      - 128
      - 128
    gnn_dropout: 0.0
    add_self_loop: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    readout: 'max'
    fc_latent_dim: []
