defaults:
  - experiments: dummy
  - models: gcn
  - datasets: bbbp
  - explainers: subgraphx
  - override hydra/job_logging: disabled
  - _self_

random_seed: 42
device_id: 0
record_filename: none
log_level: 20
console_log: True
max_ins: -1
rerun: False
result_dir: 'results'
run_id: 0
visualize: False 
retrain: False

hydra:
  run:
    dir: "."
